export const themes = {
  classic: {
    id: 'classic',
    name: 'Classic',
    preview: '/themes/classic.png',
    colors: {
      background: 'bg-[#24243A]',
      text: 'text-[#F5F2F4]', 
      button: 'bg-[#1F2937] hover:bg-[#374151]', 
      buttonText: 'text-[#F5F2F4]', 
      buttonActive: 'bg-[#479586]/90 hover:bg-[#5F9F7A]', 
      border: 'border-[#3A3A55]', 
      accent: 'bg-[#479586] hover:bg-[#5F9F7A]', 
      modalBackground: 'bg-[#121417]/95', 
      modalText: 'text-[#F5F2F4]', 
      glow: 'glow', 
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark Mode',
    preview: '/themes/dark.png',
    colors: {
      background: 'bg-gray-900',
      text: 'text-white',
      button: 'bg-gray-700 hover:bg-gray-600',
      buttonText: 'text-white',
      buttonActive: 'bg-green-600 hover:bg-green-700',
      border: 'border-gray-600',
      accent: 'bg-green-600 hover:bg-green-700',
      modalBackground: 'bg-gray-800/95',
      modalText: 'text-white',
      glow: 'glow-dark', 
    },
  },
  neon: {
    id: 'neon',
    name: 'Neon Glow',
    preview: '/themes/neon.png',
    colors: {
      background: 'bg-black',
      text: 'text-[#39FF14]', 
      button: 'bg-purple-600 hover:bg-purple-700',
      buttonText: 'text-white',
      buttonActive: 'bg-[#FF007F] hover:bg-[#CC0066]',
      border: 'border-[#00DDEB]', 
      accent: 'bg-[#FF007F] hover:bg-[#CC0066]', 
      modalBackground: 'bg-black/80',
      modalText: 'text-[#39FF14]', 
      glow: 'glow-neon', 
    },
  },
};